<?php

/**
 * @file
 * Implementation of the field storage API for DevNullDB.
 * Any data access is logged and discarded.
 */

/**
 * Implements hook_field_storage_info().
 */
function devnulldb_field_storage_field_storage_info() {
  return array(
    'devnulldb_field_storage' => array(
      'label' => t('DevNullDB field storage'),
      'description' => t('Stores nodes and fields in a DevNullDB database.'),
    ),
  );
}

/**
 * Implements hook_field_storage_details().
 */
function devnulldb_field_storage_field_storage_details($field) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_storage_create_field().
 */
function devnulldb_field_storage_field_storage_create_field($field) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_storage_update_field().
 */
function devnulldb_field_storage_field_storage_update_field($field, $prior_field, $has_data) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_storage_delete_field().
 */
function devnulldb_field_storage_field_storage_delete_field($field) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_storage_load().
 */
function devnulldb_field_storage_field_storage_load($entity_type, $entities, $age, $fields, $options) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_storage_write().
 */
function devnulldb_field_storage_field_storage_write($entity_type, $entity, $op, $fields, $entity_write = FALSE) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}


/**
 * Implement hook_field_storage_delete().
 *
 */
function devnulldb_field_storage_field_storage_delete($entity_type, $entity, $fields) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implement hook_field_storage_delete_revision().
 *
 */
function devnulldb_field_storage_field_storage_delete_revision($entity_type, $entity, $fields) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implement hook_field_storage_delete_instance().
 *
 */
function devnulldb_field_storage_field_storage_delete_instance($instance) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

class DevnullDBStorageException extends Exception {}

/**
 * Implements hook_entity_query_alter().
 *
 * Alter the entity info.
 */
function devnulldb_field_storage_entity_query_alter($query) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

function devnulldb_field_storage_field_storage_query($query) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_storage_query().
 *
 */
function devnulldb_field_storage_query($query) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_attach_rename_bundle().
 */
function devnulldb_field_storage_field_attach_rename_bundle($entity_type, $bundle_old, $bundle_new) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_entity_insert().
 */
function devnulldb_field_storage_entity_insert($entity, $entity_type) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_entity_update().
 */
function devnulldb_field_storage_entity_update($entity, $entity_type) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_field_attach_delete.
 */
function devnulldb_field_storage_field_attach_delete($entity_type, $entity) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}

/**
 * Implements hook_entity_info_alter().
 */
function devnulldb_field_storage_entity_info_alter(&$entity_info) {
  file_put_contents('php://stderr', __FUNCTION__ . " called\n");
  file_put_contents('php://stderr', "arguments: " . print_r(func_get_args(), TRUE) . "\n");
  return;
}
