<?php
/**
 * Copyright 2013 hbz NRW (http://www.hbz-nrw.de/)
 *
 * This file is part of regal-drupal.
 *
 * regal-drupal is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * regal-drupal is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with regal-drupal.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_field_info().
 */
function edoweb_field_field_info() {
  return array(
    'edoweb_ld_reference' => array(
      'label' => t('A linked data field'),
      'description' => t('This field holds the URI of a linked data resource'),
      'default_widget' => 'edoweb_autocomplete_widget',
      'default_formatter' => 'edoweb_ld_format',
      'property_type' => 'uri',
    ),
    'edoweb_date' => array(
      'label' => t('A field for dates'),
      'description' => t('This field holds dates of the format DD.MM.YYYY, MM/YYYY or YYYY'),
      'settings' => array('max_length' => 10),
      'instance_settings' => array('text_processing' => 0),
      'default_widget' => 'text_textfield',
      'default_formatter' => 'text_default',
      'property_type' => 'text',
    ),
    'edoweb_datastream' => array(
      'label' => t('A field for datastreams'),
      'description' => t('This field holds datastream URIs'),
      'instance_settings' => array('text_processing' => 0),
      'default_widget' => 'edoweb_upload_widget',
      'default_formatter' => 'edoweb_datastream_format',
      'property_type' => 'uri',
    ),
  );
}

/**
 * Implements hook_field_validate().
 */
function edoweb_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Overwrite default autocomplete behaviour
  drupal_add_js(
    drupal_get_path('module', 'edoweb_field') . '/edoweb_field_autocomplete.js',
    array('weight' => '100')
  );

  switch ($field['type']) {
    case 'edoweb_date':
      foreach ($items as $delta => $item) {
        if (!edoweb_field_field_is_empty($item, $field) &&
            !_edoweb_value_is_valid_date($item['value'])) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'edoweb_field_date_invalid',
            'message' => t('Dates must be of the form DD.MM.YYY, MM/YYYY or YYYY.'),
          );
        }
      }
      break;
    case 'edoweb_ld_reference':
      foreach ($items as $delta => $item) {
        if (!edoweb_field_field_is_empty($item, $field) &&
            !_edoweb_value_is_valid_uri($item['value'])) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'edoweb_field_uri_invalid',
            'message' => t('Value must be a valid, absolute URI.'),
          );
        }
      }
      break;
  }
}

function _edoweb_value_is_valid_date($value) {
  $pattern = '/^(\d\d\.\d\d\.\d\d\d\d|\d\d\/\d\d\d\d|\d\d\d\d)$/';
  return preg_match($pattern, $value) === 1;
}

function _edoweb_value_is_valid_uri($value) {
  /*
   * URI validation regular expression from
   * http://jmrware.com/articles/2009/uri_regexp/URI_regex.html#uri-38
   */
  $pattern = "`
    [A-Za-z][A-Za-z0-9+\-.]* :
    (?: //
      (?: (?:[A-Za-z0-9\-._~!$&'()*+,;=:]|%[0-9A-Fa-f]{2})* @)?
      (?:
        \[
        (?:
          (?:
            (?:                                                    (?:[0-9A-Fa-f]{1,4}:){6}
            |                                                   :: (?:[0-9A-Fa-f]{1,4}:){5}
            | (?:                            [0-9A-Fa-f]{1,4})? :: (?:[0-9A-Fa-f]{1,4}:){4}
            | (?: (?:[0-9A-Fa-f]{1,4}:){0,1} [0-9A-Fa-f]{1,4})? :: (?:[0-9A-Fa-f]{1,4}:){3}
            | (?: (?:[0-9A-Fa-f]{1,4}:){0,2} [0-9A-Fa-f]{1,4})? :: (?:[0-9A-Fa-f]{1,4}:){2}
            | (?: (?:[0-9A-Fa-f]{1,4}:){0,3} [0-9A-Fa-f]{1,4})? ::    [0-9A-Fa-f]{1,4}:
            | (?: (?:[0-9A-Fa-f]{1,4}:){0,4} [0-9A-Fa-f]{1,4})? ::
            ) (?:
                [0-9A-Fa-f]{1,4} : [0-9A-Fa-f]{1,4}
              | (?: (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?) \.){3}
                    (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
              )
          |   (?: (?:[0-9A-Fa-f]{1,4}:){0,5} [0-9A-Fa-f]{1,4})? ::    [0-9A-Fa-f]{1,4}
          |   (?: (?:[0-9A-Fa-f]{1,4}:){0,6} [0-9A-Fa-f]{1,4})? ::
          )
        | [Vv][0-9A-Fa-f]+\.[A-Za-z0-9\-._~!$&'()*+,;=:]+
        )
        \]
      | (?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}
           (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
      | (?:[A-Za-z0-9\-._~!$&'()*+,;=]|%[0-9A-Fa-f]{2})*
      )
      (?: : [0-9]* )?
      (?:/ (?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*
    | /
      (?:    (?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})+
        (?:/ (?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*
      )?
    |        (?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})+
        (?:/ (?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*
    |
    )
    (?:\? (?:[A-Za-z0-9\-._~!$&'()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?
    `x";
  return preg_match($pattern, $value) === 1;
}

/**
 * Implements hook_field_is_empty().
 */
function edoweb_field_field_is_empty($item, $field) {
  if (empty($item['value']) && (string) $item['value'] !== '0') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_widget_info().
 *
 * @see field_example_field_widget_form()
 */
function edoweb_field_field_widget_info() {
  return array(
    'edoweb_autocomplete_widget' => array(
      'label' => t('Auto-complete'),
      'field types' => array('edoweb_ld_reference'),
    ),
    'edoweb_upload_widget' => array(
      'label' => t('File Upload'),
      'field types' => array('edoweb_datastream'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function edoweb_field_field_formatter_info() {
  return array(
    'edoweb_ld_format' => array(
      'label' => t('Linked data URI'),
      'field types' => array('edoweb_ld_reference'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
    'edoweb_datastream_format' => array(
      'label' => t('Datastream URI'),
      'field types' => array('edoweb_datastream'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function edoweb_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();
  switch ($display['type']) {
    case 'edoweb_ld_format':
      foreach ($items as $delta => $item) {
        $elements[$delta] = array(
          '#markup' => l(_edoweb_field_ld_reference_get_label($field, $item['value']), $item['value']),
        );
      }
      break;
    case 'edoweb_datastream_format':
      foreach ($items as $delta => $item) {
        $elements[$delta] = array(
          '#markup' => l($item['value'], $item['value']),
        );
      }
      break;
  }
  return $elements;
}

/**
 * Implements hook_field_widget_form().
 *
 * hook_widget_form() is where Drupal tells us to create form elements for
 * our field's widget.
 *
 */
function edoweb_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  // Overwrite default autocomplete behaviour
  drupal_add_js(
    drupal_get_path('module', 'edoweb_field') . '/edoweb_field_autocomplete.js',
    array('weight' => '100')
  );

  switch ($instance['widget']['type']) {
    case 'edoweb_autocomplete_widget':
      $widget = $element;
      $widget['#delta'] = $delta;

      $endpoint = $field['settings']['endpoint'];
      $parameter = $field['settings']['parameter'];

      $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
      // Check if value was set in form input, e.g. when this function
      // is called by ajax via the "Add another item" button.
      $value = isset($form_state['input'][$field['field_name']]['und'][$delta]['value']) ?
        $form_state['input'][$field['field_name']]['und'][$delta]['value'] : $value;

      if ($value != '') {
        $widget += array(
          '#type' => 'hidden',
          '#autocomplete_path' => "edoweb/autocomplete/{$field['field_name']}",
          '#value' => $value,
        );
        $element['label'] = array(
          '#type' => 'textfield',
          '#value' => _edoweb_field_ld_reference_get_label($field, $value),
          '#disabled' => TRUE,
        );
      } else {
        $widget += array(
          '#type' => 'textfield',
          '#autocomplete_path' => "edoweb/autocomplete/{$field['field_name']}",
        );
      }
      $element['value'] = $widget;
      break;
    case 'edoweb_upload_widget':
      $widget = $element;
      $widget['#delta'] = $delta;
      $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
      if ($value == '') {
        $widget += array(
          '#type' => 'file',
          '#title' => t('Choose a file'),
        );
      }
      $element['value'] = $widget;
  }

  return $element;
}

function _edoweb_field_ld_reference_get_label($field, $resource_uri) {
  $api = new LinkedDataClient();
  $rdf_model = $api->getRDF($resource_uri);
  $rdf_subject = new LibRDF_URINode($resource_uri);
  LibRDF_LiteralNode::setPlainOutput(true);
  $rdf_properties = $field['settings']['label_properties'];
  $label_properties = array();
  foreach ($rdf_properties as $rdf_property_uri) {
    $rdf_property = new LibRDF_URINode($rdf_property_uri);
    try {
      // Fix escaped unicode characters such as \u00E4
      $label_properties[] = json_decode(
        '"'.$rdf_model->getTarget($rdf_subject, $rdf_property).'"'
      );
    } catch (LibRDF_LookupError $e) {
      // Property could not be loaded, ignore
    }
  }
  if (!empty($label_properties)) {
    $resource_label = implode(', ', $label_properties);
  } else {
    $resource_label = "Label for $resource_uri";
  }
  return "$resource_label";
}
